#!/usr/bin/env bash

die() {
   echo "$1" >&2
   exit 1
}

bus_to_str() {
  value="$(< /dev/stdin)"
  case $value in
    "0001") echo -n BUS_PCI;;
    "0002") echo -n BUS_ISAPNP;;
    "0003") echo -n BUS_USB;;
    "0004") echo -n BUS_HIL;;
    "0005") echo -n BUS_BLUETOOTH;;
    "0006") echo -n BUS_VIRTUAL;;
    "0010") echo -n BUS_ISA;;
    "0011") echo -n BUS_I8042;;
    "0012") echo -n BUS_XTKBD;;
    "0013") echo -n BUS_RS232;;
    "0014") echo -n BUS_GAMEPORT;;
    "0015") echo -n BUS_PARPORT;;
    "0016") echo -n BUS_AMIGA;;
    "0017") echo -n BUS_ADB;;
    "0018") echo -n BUS_I2C;;
    "0019") echo -n BUS_HOST;;
    "001A") echo -n BUS_GSC;;
    "001B") echo -n BUS_ATARI;;
    "001C") echo -n BUS_SPI;;
    "001D") echo -n BUS_RMI;;
    "001E") echo -n BUS_CEC;;
    "001F") echo -n BUS_INTEL_ISHTP;;
    "0020") echo -n BUS_AMD_SFH;;
    *) echo 0x${value};;
  esac
}

group_to_str() {
  value="$(< /dev/stdin)"
  case $value in
    "0001") echo -n HID_GROUP_GENERIC;;
    "0002") echo -n HID_GROUP_MULTITOUCH;;
    "0003") echo -n HID_GROUP_SENSOR_HUB;;
    "0004") echo -n HID_GROUP_MULTITOUCH_WIN_8;;
    "0100") echo -n HID_GROUP_RMI;;
    "0101") echo -n HID_GROUP_WACOM;;
    "0102") echo -n HID_GROUP_LOGITECH_DJ_DEVICE;;
    "0103") echo -n HID_GROUP_STEAM;;
    "0104") echo -n HID_GROUP_LOGITECH_27MHZ_DEVICE;;
    "0105") echo -n HID_GROUP_VIVALDI;;
    *) echo 0x${value};;
  esac
}


command -v udevadm > /dev/null || die "The udevadm command is required"

for dev in /sys/bus/hid/devices/*; do
  modalias=$(udevadm info "$dev" | grep "MODALIAS" | sed -e "s/.*MODALIAS=hid://")
  bus=$(echo $modalias | sed 's/b\(.*\)g.*/\1/' | bus_to_str)
  group=$(echo $modalias | sed 's/.*g\(.*\)v.*/\1/' | group_to_str)
  vid=$(echo $modalias | sed 's/.*v0000\(.*\)p.*/\1/')
  pid=$(echo $modalias | sed 's/.*p0000\(.*\)/\1/')
  name=$(udevadm info "$dev" | grep "HID_NAME" | sed -e "s/.*HID_NAME=//")
  echo "$dev"
  echo "  - name:         $name"
  echo "  - modalias:     $modalias"
  echo "  - device entry: HID_DEVICE(${bus}, ${group}, 0x${vid}, 0x${pid})"
done
